name: photo-studio-saas

services:
  backend:
    image: nongdev/photo-studio-backend:latest
    container_name: photo_studio_backend
    restart: always
    volumes:
      - photo_studio_storage:/var/www/html/storage
      - ./backend/bootstrap/cache:/var/www/html/bootstrap/cache
    env_file:
      - ./backend/.env
    networks:
      - web
      - internal_photo_studio

  webserver:
    image: nongdev/photo-studio-webserver:latest
    container_name: photo_studio_webserver
    restart: always
    ports:
      - "85:80"
    volumes:
      - photo_studio_storage:/var/www/html/storage
    networks:
      - web
      - internal_photo_studio
    depends_on:
      - backend

  horizon:
    image: nongdev/photo-studio-backend:latest
    container_name: photo_studio_horizon
    restart: always
    command: php artisan horizon
    volumes:
      - photo_studio_storage:/var/www/html/storage
    env_file:
      - ./backend/.env
    networks:
      - web
      - internal_photo_studio

  scheduler:
    image: nongdev/photo-studio-backend:latest
    container_name: photo_studio_scheduler
    restart: always
    command: >
      sh -c "while true; do php artisan schedule:run --verbose --no-interaction; sleep 60; done"
    volumes:
      - photo_studio_storage:/var/www/html/storage
    env_file:
      - ./backend/.env
    networks:
      - web
      - internal_photo_studio

  frontend:
    image: nongdev/photo-studio-frontend:latest
    container_name: photo_studio_frontend
    restart: always
    networks:
      - web

networks:
  web:
    external: true
  internal_photo_studio:
    driver: bridge

volumes:
  photo_studio_storage:
